export default {
  translation: {
    changeLang: 'Русский',
    auth: {
      login: 'Log in',
      signup: 'Sign up',
      userName: 'User name',
      enterName: 'enter name',
      password: 'Password',
      enterPassword: 'enter password',
      passwordConfirm: 'Confirm password',
      repeatPassword: 'repeat your password',
      submit: 'Send',
      orSignup: 'or signup',
    },
    controls: {
      addChannel: 'Add',
      changeChannel: 'Change',
      deleteChannel: 'Delete',
      sendMessage: 'Send',
      enterMessage: 'enter your message',
      logout: 'Log out',
      colorTheme: 'Theme',
      lang: 'ru',
    },
    modals: {
      createChannel: 'Create channel',
      channelName: 'channel name',
      create: 'Create',
      renameChannel: 'Rename channel',
      newName: 'type new name',
      update: 'update',
      confirmDelete: 'Are you shure?',
      removeChannel: 'Remove channel',
      yes: 'Yes',
      no: 'No',
    },
    validationErrors: {
      required: 'This is required field',
      charMin: 'must contain at least {{n}} characters',
      charMax: 'must contain no more than {{n}} characters',
      must_mutch: 'Passwords must mutch',
      already_in_use: 'Sorry, name already in use',
      connection_lost: 'Network error',
    },
    headers: {
      channels: 'Channels',
      message: '{{count}} Message',
      message_plural: '{{count}} Messages',
    },
  },
};
