export default {
  translation: {
    changeLang: 'English',
    auth: {
      login: 'Вход',
      signup: 'Регистрация',
      nickname: 'Ваш ник',
      userName: 'Имя пользователя',
      enterName: 'ваш ник',
      password: 'Пароль',
      enterPassword: 'ваш пароль',
      passwordConfirm: 'Подтвердите пароль',
      repeatPassword: 'повторите пароль',
      submit: 'Войти',
      make_registration: 'Зарегистрироваться',
      orSignup: 'Регистрация',
    },
    controls: {
      addChannel: '+',
      changeChannel: 'Изменить',
      deleteChannel: 'Удалить',
      sendMessage: 'Отправить',
      enterMessage: 'Ваше сообщение',
      logout: 'Выход',
      colorTheme: 'Тема',
      lang: 'en',
    },
    modals: {
      createChannel: 'Создать канал',
      channelName: 'ваше название',
      create: 'Отправить',
      renameChannel: 'Сменить название',
      newName: 'новое название',
      update: 'Изменить',
      confirmDelete: 'Подтвердите',
      removeChannel: 'Удалить канал',
      yes: 'Да',
      no: 'Нет',
    },
    validationErrors: {
      required: 'Обязательно для заполнения',
      passLength: 'Не менее 6 символов',
      nameLength: 'От 3 до 20 символов',
      must_match: 'Пароли должны совпадать',
      already_in_use: 'Извините, имя занято',
      connection_lost: 'Ошибка сети',
      incorrect_name_pass: 'Неверные имя пользователя или пароль',
      charMax: 'Не более 30 символов',
    },
    headers: {
      channels: 'Каналы',
      message_0: '{{count}} Сообщение',
      message_1: '{{count}} Сообщения',
      message_2: '{{count}} Сообщений',
    },
  },
};
